version: '3.9'

services:
  webserver:
    image: nginx
    container_name: webserver
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      # Nginx conf
      - ./nginx:/etc/nginx/conf.d
      # Certtbot
      - /path/certbot/conf:/etc/letsencrypt:ro
      - /path/certbot/www:/var/www/certbot:ro
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: always
    volumes:
      - /path/certbot/conf:/etc/letsencrypt:rw
      - /path/certbot/www:/var/www/certbot:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
